### PR TITLE
AnalysisMode.COMMITS doesn't exist

### PR DESCRIPTION
**Pull request by exterm**
Remove from config.py docs.

### CODE REVIEW

**Comment by nicolasriquet** [comment]
Thank you for spotting this. :)

**Comment by exterm** [comment]
Thank you for merging this 😄

**Comment by exterm** [comment]
Oh and thank you for making this code available in the first place.

**Comment by nicolasriquet** [comment]
You're welcome! I'm glad you like it. :)

You may find our paper interesting as well: https://xdevroey.be/publication/riquet-2022/riquet-2022.pdf. It explains how we used GitDelver to produce the GDED dataset (which might be useful too): https://zenodo.org/record/5838537#.Y4CsS9eZOUk.

Don't hesitate to suggest other improvements!

Regards,
Nicolas

**Comment by exterm** [comment]
Yes, I stumbled upon this repository after reading the paper 🙂 thank you!

**Comment by nicolasriquet** [comment]
Great! Don't hesitate to contact me if you have questions. :-)

**Pull request merged**
